# Generated by Django 5.2.1 on 2025-07-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreDefineTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_code', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tool_images/')),
            ],
            options={
                'db_table': 'PreDefineTools',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_code', models.CharField(max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tool_images/')),
                ('borrowed_quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'Tool',
            },
        ),
    ]
