# Generated by Django 5.2.1 on 2025-07-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LesseeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('lessee_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('tool_code', models.CharField(max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('return_date', models.DateField(null=True)),
                ('security_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('security_amount_status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Returned', 'Returned'), ('Overdue', 'Overdue'), ('Not Returned', 'Not Returned')], default='Not Returned', max_length=20)),
                ('tool_status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Returned', 'Returned'), ('Overdue', 'Overdue'), ('Not Returned', 'Not Returned')], default='Ongoing', max_length=20)),
                ('is_overdue', models.BooleanField(default=False)),
                ('overdue_date', models.DateTimeField(blank=True, null=True)),
                ('overdue_days', models.IntegerField(blank=True, null=True)),
                ('id_document_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('driving_license', 'Driving License')], max_length=30)),
                ('id_document_number', models.CharField(max_length=50)),
                ('doc_status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Returned', 'Returned'), ('Overdue', 'Overdue'), ('Not Returned', 'Not Returned')], default='Not Returned', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('extra_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'LesseeDetail',
            },
        ),
    ]
